### ISSUE TITLE
Please make generated trait pub

### ISSUE THREAD

**Issue by Boscop** [mexus/unzip-n#1]
Please make generated trait `pub`, so that it can be used from other modules :)

**Comment by mexus** [comment]
Sure np, I guess we could add an optional visibility modifier to the macro call.

**Comment by mexus** [comment]
Done! That was an easy one :) `0.1.2` on crates.io!

**Comment by Boscop** [comment]
@mexus Thanks, that was quick :)

**Comment by mexus** [comment]
It's always quick when it's simple and it's always long when it's complicated :)
